define([
		"API",
		"Utils",
		"WidgetInjector",
		"LoginModel",
		"PriceListModel",
		"LoginViewCtrl",
		"PriceListViewCtrl"
		],
	function(API,Utils,WidgetInjector,loginModel,
			 priceListModel,LoginViewCtrl,PriceListViewCtrl){
				return {
					myAPI:API,
					utils:Utils,
					widgetInjector:WidgetInjector,
					components:{
						login:{
							view:LoginViewCtrl,
							model:loginModel
						},
						priceList:{
							view:PriceListViewCtrl,
							model:priceListModel
						}
					}
				}
});
